### ISSUE TITLE
Styling issues 

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/rocrate-preview-widget#21]
- [x] : nog teveel kleur --> switch kleur van background naar foreground (font)
- [x] : betere icons voor "metadata"and "preview" (download is ok)
- [x] : msch zelfs volgorde wijzigen --> eerst preview, dan metadata?
- [x] : breadcrum inject na de root (huisje) richting graph (wereldbol) ofte content (map) 
- [x] : html aanpassen zodat html/head/title de naam van de package (en release) bevat : "data_workspace (draft)  :: RO-Crate  Preview" 
- [x] : Herorder breadcrumb + buttons op 1 lijn
- [x] : colabsable metadata (laagste prio van al deze zelfs)

**Comment by cedricdcc** [comment]
@marc-portier . Kan deze issue gesloten worden? 
**https://cedricdcc.github.io/test_single_rocrate/**

**Comment by marc-portier** [comment]
some extra / remaining remarks:

- [ ] icons to be changed (metadata == something that evokes list/table/structure not eye, nor graphql) --> 
![image](https://github.com/vliz-be-opsci/rocrate-preview-widget/assets/299574/77567347-5f53-4e21-962b-659ba8290483)
- [ ] html escape issue on the error message if no viewer is available --> 
![image](https://github.com/vliz-be-opsci/rocrate-preview-widget/assets/299574/53867d42-9dc5-4607-85ff-de2502967b11)
- [ ] drop the bullet disk on lists --> 
![image](https://github.com/vliz-be-opsci/rocrate-preview-widget/assets/299574/6aed83e8-3173-4b83-9e43-84c08dbfb860)
- [ ] top level doesn't provide entry into the "graph" section -- also: if no graph entries are there - it would still be nice if that fact is apparent (e.g. showing the option greyed out / count zero / ...)
![image](https://github.com/vliz-be-opsci/rocrate-preview-widget/assets/299574/9814fe37-8a94-42ff-981d-0602c266ed7c)
- [ ] what list of previewers is now included / what mime types supported ? -- please add markdown view (as html if possible, as pre-formatted text at least)
